version: "3"
services:
  proxy:
    image: ubuntu/squid:edge 
    ports:
      - "3128:3128"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./passwords:/etc/squid/passwords
      - ./spool:/var/spool/squid
      - ./log:var/log/squid
    restart: always
